# Generated by Django 5.2 on 2025-04-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
