# Generated by Django 5.2 on 2025-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_category_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
