# Generated by Django 5.2 on 2025-07-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_category_parent_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
