# Generated by Django 5.2 on 2025-07-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='province',
            field=models.CharField(blank=True, choices=[('ON', 'Ontario'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('AB', 'Alberta'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NT', 'Northwest Territories'), ('YT', 'Yukon'), ('NU', 'Nunavut')], max_length=2),
        ),
    ]
