# Generated by Django 5.2 on 2025-07-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('urgent', 'Urgent'), ('top', 'Top')], max_length=10, null=True),
        ),
    ]
