# Generated by Django 5.2 on 2025-08-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_userprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seller_type',
            field=models.CharField(choices=[('individual', 'Seller'), ('store', 'Store'), ('business', 'Business')], default='individual', max_length=20),
        ),
    ]
