# Generated by Django 5.2 on 2025-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
