# Generated by Django 5.2.8 on 2025-12-02 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_listing_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='listing',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_listings', through='board.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
