# Generated by Django 5.2.8 on 2025-12-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0030_alter_favorite_options_listing_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_listings',
        ),
    ]
