# Generated by Django 5.2.8 on 2025-12-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0032_alter_favorite_listing_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('urgent', 'Urgent'), ('top', 'Top')], max_length=20, null=True),
        ),
    ]
