# Generated by Django 5.2.8 on 2025-12-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0034_userprofile_show_email_userprofile_show_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hide_personal_info',
        ),
    ]
